# Font
font_family Hack Nerd Font
font_size 11.0
disable_ligatures never

# Background
background_opacity 0.85
background_blur 1

# Layout
remember_window_size no
remember_window_position no
window_padding_width 8

# Dracula theme
include Dracula.conf