# Set the range of the refresh rate slider in the Steam client
export STEAM_DISPLAY_REFRESH_LIMITS=60,120,144,165

# Specify if you want to enable support for HDR content
ENABLE_GAMESCOPE_HDR=1

# Set the target luminace of the inverse tone mapping process (option)
GAMESCOPE_HDR_NITS=400

# Override entire client command line
CLIENTCMD="env DKVK_HDR=1 steam -steamdeck -steamos3 -pipewire-dmabuf"

# Override the entire Gamescope command line
# This will not use screen and render sizes above
GAMESCOPECMD="gamescope --steam --fullscreen -W 2560 -H 1440 -r 120 --hdr-enabled --hdr-itm-enabled --adaptive-sync"